name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Set system language to Spanish
        run: |
          sudo apt-get install -y language-pack-es
          sudo update-locale LANG=es_ES.UTF-8

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set Chrome language to Spanish
        run: |
          echo "export CHROME_ARGS=--lang=es" | sudo tee -a /etc/environment
          echo "export CHROME_ARGS=--lang=es --force-language=es --lang=es_ES --lang=es_ES.UTF-8" | sudo tee -a /etc/environment
          source /etc/environment

      - name: Run Cypress tests on Chrome in Spanish
        run: |
          export LANG=es_ES.UTF-8
          export LANGUAGE=es_ES.UTF-8
          export LC_ALL=es_ES.UTF-8        
          npx cypress run --browser chrome
